django4/django4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from common import views
## for standalone photos entry app
import readme

urlpatterns = [

    path('', readme.show_readme),
    path('howto/docker/', readme.docker_readme),
    path('admin/', admin.site.urls),

    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.ico')),
    path('robots.txt', RedirectView.as_view(url='/static/robots.txt')),
##    path('salicicola/', views.salicicola),
##
##
    path('names/', include('names.urls')), 
##    path('bugs/', include('bugs.urls')), 
##    path('photodb/checklist/', include('checklist.urls_flat')), ## checklist_
##    path('photodb/vascular/checklist/', include('checklist.urls_tree')), ## checklist_
##    path('', RedirectView.as_view(url='/photodb/checklist/about/')),
##
path('photodb/', include('photodb.urls')),    
path('photodb/', include('gallery.urls_vascular')),
path('photodb/', include('gallery.urls_gallery')),
path('photodb/', include('photodb.urls_edit')),
##
path('gis/', include('gisapp.urls')),
    
##
    path('servlet/GetImage', views.GetImage),
##    path('servlet/CaptionEditorNew', views.CaptionEditor),

path('photos/', include('photos.urls')),
##path('townmapper/', include('townmapper5.urls')),
##path('herbarium/', include('herbarium.urls')),
##
##path('flora/', include('flora.urls')),
##path('flora/deane/', include('deane96.urls')),
##    
##path('inaturalist/', include('inaturalist.urls')),
##path('LC/', include('LC.urls')),

## no such table: deane96_plantname
##path('flora/deane/', include('deane96.urls')),
]

django4/names/urls.py
from django.urls import path
from . import edit, views, checklist, invasive, get_exotic

## /names/~
urlpatterns = [
path('', views.get_core),
path('vascular/invasive/', invasive.invasive_index, {"template":"names/invasive_index.htm"}),
path('vascular/invasive/<str:show>/', invasive.get_invasive, {"template":"names/invasive.htm"}),

path('vascular/flexible/', checklist.taxa_index, {"mode": "flexible", "template":"names/checklist_nonlegacy_byfams2.htm", "state": ""}), 
path('vascular/flexible/<int:pnid>/', views.get_html, {"state": ""}), 

path('vascular/fixed/',               checklist.taxa_index, {"mode": "fixed", "template":"names/checklist_nonlegacy_byfams.htm"}), 
path('vascular/fixed/<int:fid>/',     checklist.checklist_family, {"template":"names/checklist_nonlegacy_family_new.htm","mode":None}), 
path('vascular/fixed/<int:fid>/all/', checklist.checklist_family, {"template":"names/checklist_nonlegacy_family_new.htm", "mode":"all", "authorized_cnh":True}),

path('edit/name/<int:pnid>/',   edit.edit_name_mini, {'template': 'names/form_namemini.htm'}), 
path('delete/name/<int:pnid>/', edit.delete_name_legacy_name),
path('add/synonym/<int:spid>/', edit.add_syn),

path('xml/<int:pnid>/',             views.get_xml, {"state": ""}), 
path('xml/<int:pnid>/<str:state>/', views.get_xml),

path('vascular/exotic/', get_exotic.exotic),

]

django4/names/models.py
import datetime, time, uuid 
from django.db import models
from django_random_id_model import RandomIDModel
## alternatively can try UUID, very big integers are not supported by SQLite

## contains three recursive relationships but old one (using fields legacy_parent, sal_latname, sal_authors)
## is not supported anymore; fields aren't removed (if alternative classification would be needed)
## standard classification (fixed hierarchy) used fields: level, and parent
class Name (models.Model):
    pnid = models.AutoField(primary_key=True)
    category = models.CharField(max_length=50, blank=True, default="vascular") ## FIXME: error prone 
    latname = models.CharField(max_length=150, blank=True)  ## when entirely normalized, must be one word
    authors = models.CharField(max_length=150, blank=True)
    colnames = models.CharField(max_length=150, blank=True) ## separated by comma, only most common ones to be shown in views, 
    longname = models.CharField(max_length=250, blank=True) ## is it in use? Could it be removed?
    note = models.TextField(blank=True)                 ## for private usage (admins)
    caption = models.TextField(blank=True, default="")  ## for public view, both should accept XHTML fragments, i.e. may contain <i>...</i>
    excluded = models.BooleanField(default=False) ## i.e, the taxon could to be deleted
    disabled = models.BooleanField(default=False, verbose_name="uncertain") ## similar to excluded, perhaps one of them could be deleted in future versions
    ## modified to remove eleocharis vars
    ## flexible hierarchy:
    rank = models.CharField(max_length=50, blank=True, verbose_name="actual rank") ## by mistake was called level in very first versions
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)

    ## fixed hierarchy:
    level = models.CharField(max_length=50, blank=True) ## group, etc = elementName , was called rank in very first versions
    upper = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name="Fid_Gid") ## 
    
    ## legacy classification:
    legacy_parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name="legacy_upper")
    sal_latname = models.CharField(max_length=150, blank=True) ## sal name if not  = ccss
    sal_authors = models.CharField(max_length=150, blank=True)    

    ## technicall, auto filled
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    uid = models.CharField(max_length=10, blank=True, default="") ## auto filled if empty: see admin.py

    def __str__(self):
        ##return("%s: %s / %s" % (self.pnid, self.latname, self.sal_latname))
        if self.longname:
            return ("%s: %s" % (self.pnid, self.longname))
        else:
            return ("%s: %s" % (self.pnid, self.latname))

    @property
    def formatted_name(self):
        if self.rank == 'subspecies':
            abb = "sp."
        elif self.rank == 'variety':
            abb = "var."
        elif self.rank == 'forma':
            abb = "f."
##        elif self.rank == 'hybrid':
##            abb = "×"
        else:
            abb = ""
        if self.rank == 'subspecies' or self.rank == 'variety' or self.rank == 'forma':
            genus = self.upper.latname
            sp_latname = self.parent.latname
            parent_authors = self.parent.authors
            latname = self.latname
            authors = self.authors
            if latname == sp_latname:
                formatted = "<i>%s %s</i> %s %s <i>%s</i>" % (genus, sp_latname, parent_authors, abb, latname)
            else:
                formatted = "<i>%s %s</i> %s <i>%s</i> %s" % (genus, sp_latname, abb, latname, authors)
        elif self.rank == 'hybrid':
            formatted = "<i>%s</i>" % self.longname
        elif self.rank == 'species':
            formatted = "<i>%s</i> %s" % (self.longname, self.authors)
        elif self.rank == 'genus' or self.parent.rank == 'genus':
            formatted = "<i>%s</i> %s" % (self.latname) ## <i> or not <i>  upper? FIXME
        else:
            formatted = self.latname ## if above genus
        print ("will return", repr(formatted))
        return "XXX %s" % formatted

    class Meta:
        verbose_name_plural = 'NameRecords'

class CommonName(models.Model):
    ref_name = models.ForeignKey(Name, on_delete=models.RESTRICT)
    colname = models.CharField(max_length=150, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return("%s: %s [%s]" % (self.ref_name.latname, self.colname, self.created))

    class Meta:
        unique_together = ('ref_name', 'colname')

##class NameAnnotation(RandomIDModel):
##    ## with RandomIDModel id appears in form ! Set exclude in admin
##    plant = models.ForeignKey(Name, on_delete=models.RESTRICT)
##    note = models.TextField(max_length=520, blank=True, null=True)
##    url = models.URLField(max_length=255, blank=True, null=True)
##    page = models.TextField(max_length=520, blank=True, null=True) ## link to salicicola page must be started with /
##    cached = models.CharField(max_length=255, blank=True, null=True, help_text="saved filename") ## applied only if kind = photo
##    ## slugField should not contains period though "the value in the SlugField is only checked in forms, not in the database." ## could add custom save() [see below example] but hardly needed
##    kind = models.CharField(max_length=50, choices = (
##            ('', ''),
##            ('note', 'note without photo'),
##            ('photo', 'photo'),
##            ('sample', 'to sample'),
##            ('check', 'relocate'),
##            ('invasive_link', 'invasive link'), ## must have page or url non empty
##        )) 
##    by = models.CharField(max_length=50,  blank=True, null=True) ## AZ , blank=True, default=""
##    created = models.DateTimeField(auto_now_add=True)
##    modified = models.DateTimeField(auto_now=True)
##
##    def __str__(self):
##        return("%s: [%s] %s %s" % (self.pk, self.plant, self.kind, self.url))

class NameAnnotation(models.Model):
    UUID = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False) ## id
    ##id = models.IntegerField(blank=True, null=True)
    plant = models.ForeignKey(Name, on_delete=models.RESTRICT)
    note = models.TextField(max_length=520, blank=True, null=True)
    url = models.URLField(max_length=255, blank=True, null=True)
    page = models.TextField(max_length=520, blank=True, null=True) ## link to salicicola page must be started with /
    cached = models.CharField(max_length=255, blank=True, null=True, help_text="saved filename") ## applied only if kind = photo
    ## slugField should not contains period though "the value in the SlugField is only checked in forms, not in the database." ## could add custom save() [see below example] but hardly needed
    kind = models.CharField(max_length=50, choices = (
            ('', ''),
            ('note', 'note without photo'),
            ('photo', 'photo'),
            ('sample', 'to sample'),
            ('check', 'relocate'),
            ('invasive_link', 'invasive link'), ## must have page or url non empty
        )) 
    by = models.CharField(max_length=50,  blank=True, null=True) ## AZ , blank=True, default=""
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return("%s: [%s] %s %s" % (self.pk, self.plant, self.kind, self.url))
   
## must not be empty: all taxa (at least vascular) at species level must have meta record
class SpeciesMeta (models.Model):
    spid = models.IntegerField(primary_key=True) ## == pnid or ccss ???
    species = models.OneToOneField(Name, blank=True, null=True, unique=True, on_delete=models.RESTRICT)  ## from foreign since it is unique
    evergreen=models.CharField(max_length=150, blank=True)
    introduced=models.CharField(max_length=150, blank=True, verbose_name="NonNative")
    invasive_mipag=models.CharField(max_length=150, blank=True)
    invasive=models.CharField(max_length=150, default="", blank=True)
    origin=models.CharField(max_length=150, blank=True)
    rare=models.CharField(max_length=150, blank=True)
    updated=models.DateTimeField(auto_now=True)
    ## from CCSS
    counties=models.CharField(max_length=150, blank=True, default="* * * * * * * * * * * * * *")
    counties_changed_from = models.CharField(max_length=150, blank=True)
    status=models.CharField(max_length=150, blank=True)
    initial_name = models.CharField(max_length=150, blank=True)
    rank = models.CharField(max_length=150, blank=True, default="species")
    notes = models.TextField(blank=True, null=True, default="")
    
    def __str__(self):
        return str(self.spid)
    class Meta:
        verbose_name_plural = 'SpeciesMeta'

django4/names/templates/names/checklist_nonlegacy_byfams.htm
<html>
    <head>
	    {%include 'names/head'%}
    </head>
	<body style="padding:1em;">
		{%include 'names/common_head' %}
		{%include 'names/checklist_header' %}
			{%for group in tree %}
				<h3>
					{{group.higher.latname}} {%if group.higher.colnames %} &#8212; {{group.higher.colnames}} {%endif%}
				</h3>
				{%for fam in group.fams %}
					<div style="padding-left:1em" id="{{fam.fam.latname}}">
						{%if fam.species %}
                    		<a title="{{fam.genera|length}}::{{fam.species}}" target="_blank" href="/names/vascular/fixed/{{fam.fam.pnid}}/">{{fam.fam.latname}}</a>
						{%else%}
							<span title="no relevant species: {{fam.species}} spp in {{fam.genera|length}} genera">{{fam.fam.latname}}</span>
						{%endif%}
					</div>
				{%endfor%}
			{%endfor%}
			{%include "names/checklist_index_footer"%}
	</body>
</html>

django4/names/templates/names/checklist_nonlegacy_byfams2.htm
<html>
	<head>
		{%include 'names/head'%}
		<script type="text/javascript">
			function collapse_expand(o, name) {
				var ref = name+':genera';
				d=document.getElementById(ref);
				if (d.style.display=='block') {
					d.style.display='none';
					//o.innerHTML = 'expand';
				}
				else {
					d.style.display='block';
					//o.innerHTML = 'collapse';
				}
			}
			function collapse_expand_all() {
				divs = document.getElementsByTagName('div');
				for (i=0; i < divs.length; i++) {
					d = divs[0];
					if (d.className == 'genera') {;
						if (d.style.display=='block') {
							d.style.display=='none';
						}
						else {
							d.style.display=='block';
						}			
					}
				}
			}
			function expandClass(thisTag, tag) {
			  var els = document.getElementsByTagName(tag);
				for (i = 0; i < els.length; i++) {
				  var ele = els[i]; 
					if (ele.className=='container') {	
					  //alert(ele);
					  current = ele.style.display;
					  if (current=='none') {
						  ele.style.display='block';
							thisTag.innerHTML = 'Collapse List';
						}
						else {
						  ele.style.display='none';
							thisTag.innerHTML = 'Expand List';
						}
				  }
				}
			}
		</script>
	</head>
	<body style="padding:1em;">
		{%include 'names/common_head' %}
		{%include 'names/checklist_header' %}
		<h3 style="margin-bottom:2ex;" onclick="expandClass(this, 'DIV')">Expand/Collapse List</h3>
		{%for group in tree %}
			<h3>{{group.higher.latname}} {%if group.higher.colnames %} &#8212; {{group.higher.colnames}} {%endif%}</h3>
			{%for fam in group.fams %}
				<div style="padding-left:1.5em" id="{{fam.fam.latname}}">
					{% if fam.genera %}
						{%if state %}
							<a title="{{fam.genera|length}}:{{fam.species}}" target="_blank" href="/names/vascular/flexible/{{fam.fam.pk}}/">{{fam.fam.latname}}</a>
						{%else%}
							<a title="{{fam.genera|length}}:{{fam.species}}" target="_blank" href="/names/vascular/flexible/{{fam.fam.pk}}/">{{fam.fam.latname}}</a>
						{%endif%}
					{%else%}
						<span title="{{fam.genera|length}}:{{fam.species}}">{{fam.fam.latname}}</span>
					{%endif%}
					&nbsp;&nbsp;
					{% if fam.genera %}
						<img class="switchview" onclick="collapse_expand(this, '{{fam.fam.latname}}')" src="/static/images/udarrow.gif" style="height: 1.2ex; padding:0; margin:0; border-width:0" vspace="0" hspace="0" border="0"> 
					{%endif%}
					<div style="margin:0;padding:0;display:none" id="{{fam.fam.latname}}:genera" class="container">
						{% for genus in fam.genera %}
                        	{%if genus.species %}
								<div style="padding-left:1.5em" id="{{genus.latname}}">
									<span>
										{%if state %}
											<a target="_blank" href="/names/vascular/flexible/{{genus.pnid}}/">{{genus.latname}}</a>
										{%else%}
											<a target="_blank" href="/names/vascular/flexible/{{genus.pnid}}/">{{genus.latname}}</a>
										{%endif%}
                                    	({{genus.species}} species)
									</span>
                            		{%if genus.subgenera %}
                                		{%for subgenus in genus.subgenera%}
		                                	<div  style="padding-left:1.5em" id="{{genus.latname}}:{{subgenus.latname}}">
		                                    	<span>
											    	{%if state %}
											        	<a target="_blank" href="/names/vascular/flexible/{{subgenus.pnid}}/">{{subgenus.latname}}</a>
											    	{%else%}
											        	<a target="_blank" href="/names/vascular/flexible/{{subgenus.pnid}}/">{{subgenus.latname}}</a>
		                                        	{%endif%}
		                                    	</span>
		                                	</div>
                                		{%endfor%}
                            		{%endif%}
								</div>
                        	{%endif%}
						{%endfor%}
					</div>
				</div>
			{%endfor%}
		{%endfor%}
		{%include "names/checklist_index_footer"%}
	</body>
</html>

django4/names/templates/names/invasive.htm
<html>
    <head>

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		{%include 'names/head'%}
		<style type="text/css">
		a {
		text-decoration:none;
		}

		@media only screen and (min-width: 990px) {
			td.left {
				width:17em;
			}
			td.right {
				width:40em;
			}
		}
		</style>
    </head>
	<body>
		{%include 'names/common_head' %}
		<h2 style="max-width:50em">
    		<span style='white-space: nowrap;' title="filter: {{show}}: {{metarecs|length}} taxa">
				Invasive Vascular Plants of Massachusetts <!--&#8212; {{metarecs|length}} Species--><br/>
                <span style="font-weight:normal;font-size:90%">
				{%if show == 'all'%} <!-- in url all ? -->
					Shows all plants with at least one of two fields not empty: invasive by Salicicola and/or by MIPAG
				{%elif show == 'official'%} <!-- in url: mipag-->
					Filtered. Only plants accepted by MIPAG are shown
				{%elif show == 'invasive'%}  <!-- in url ??? -->
					Filtered. Only plants accepted by MIPAG as 'Invasive' are shown
				{%elif show == 'likely'%}
					Filtered. Only plants defined by MIPAG as 'Likely invasive' are shown
				{%elif show == 'potentially'%}
					Filtered. Only plants defined by MIPAG as 'Potentially invasive' are shown
				{%elif show == 'rejected'%}
					Filtered. Only plants defined by MIPAG as 'Do not list at this time' are shown
				{%elif show == 'mipagall'%}
					Filtered. Only plants considered by MIPAG are shown

				{%elif show == 'other'%} <!-- other/notofficial -->
					Filtered. Only plants not accepted by MIPAG are shown
                {%else%}
                    Filtered: <span style="color:red">template error: unnknonw {{show}} attribute</span>
				{%endif%}	
                </span>			
			</span>
			<br/>
			<span style="font-weight:normal;font-size:90%">Click on the Latin name to see photos (not available for all species)</span>
            <br/>
<span style="font-weight:normal;font-size:80%">
            Available:
            [<a href="/names/vascular/invasive/all/">all records, i.e., not filtered</a>] <!-- 122  -->
            [<a href="/names/vascular/invasive/other/">Salicicola and rejected by MIPAG</a>] <!-- 45  -->
            <br/>MIPAG only: 
            [<a href="/names/vascular/invasive/invasive/">invasive] <!-- 42  -->
            [<a href="/names/vascular/invasive/potentially/">potentially invasive</a>] <!-- 3  -->
            [<a href="/names/vascular/invasive/likely/">likely invasive</a>] <!-- 32  -->
            [<a href="/names/vascular/invasive/rejected/">rejected</a>] <!-- 20  -->
            [<a href="/names/vascular/invasive/mipagall/">all in MIPAG</a>] <!-- 97  -->
</span>
		</h2>
<div class="debug" style="padding-left:1em;color:black;display:none"> 
    <ol><b>TEMP/TODO NOTES</b> (remove when published on the Web): 
<!--    <li> to show internal and external links and notes only if they are present</li>
    <li> to use modified SpeciesAnnotation for both kind of links</li>
    <li> to use InvasiveMeta only for external sites IDs : then can generate external links (not in use now)</li>
-->
    <li> to allow [salicicola-]invasive field be empty or having value 'Introduced'</li>
    <li> to add subheader with explanations, and</li>
<!--    <li> to add links to other filtered views [optional?]</li> -->
    <li> to check all categories of MIPAG defined species</li>
    <li> to show in gray species without photos at salicicola</li>
<!--    <li> suppresst equal</li>
    <li> dedicated page </li>-->
    </ol>
    <div style="padding-left:1em;padding-bottom:2ex" title="Notes for developers and/or admins [names.version: ##{{version}}]">
    Technically,  <i>InvasiveVascularPlants</i> module located in the core package 'names' and use SQLite table <b>names_name</b> 
    (field 'caption' will be shown as 'Notes'),
    <b>names_speciesmeta</b> (which has two relevant fields for invasive status: 'invasive_mipag' and 'invasive'[_salicicola]), and 
    table <b>names_speciesannotation</b>:
    field 'page' used for internal (dedicated) webpage (presumably only one page for a species) and value must starts with '/',
    and field 'url' for external links (may have numerous annotation records for the same plant species),
    in both cases flag 'kind' must be 'invasive_link';
    besides it needs files 'invasive.py (with referenced checklist.py) and templates/names/invasive.htm.
    Presence of 'townmapper' (needed for town level maps) and 'photodb' apps optional (if missing, 
    links may lead to another server, e.g., web based salicicola.com (or 172.104.19.75) but availability of photos cannot be checked.
    For sake of simplicity,
    <i>edit</i> links provided for any authenticated, even if not authorized user (who could not actually add or edit records).
    </div>
</div>
		<div>
			{%for rec in metarecs %}
{%if not rec.species.excluded %} <!-- excluding var vegetus -->
				<div style="padding-left:2ex" id="{{rec.species.longname|safe}}">
					<a target="_blank" href="{{server}}/photodb/gallery/view/{{rec.species.pk}}/">{{rec.species.longname|safe}}</a>
					{{rec.species.authors}}
					{%if rec.species.colnames%}
						[{{rec.species.colnames}}] 
					{%endif%}
					&#8212; [<a target="tmap" href="{{mapserver}}/townmapper/spid/{{rec.species.pk}}/">map by town</a>] 
                        {% for ann in rec.species.nameannotation_set.all%}
                            {%if ann.page %}
                            [<a href="/{{ann.page}}">dedicated page</a>]
                            {%endif%}
                        {%endfor%}
					<div style="padding-left:2ex;"> 
					<table border="0">
						<tr>
							<td nowrap="true" class="left">
								MA Counties
							</td>
							<td class="right">
								{%for c in tcounties %}
									<span title="{{c.1}}" style="display: inline-block;width:2em;background-color:#EEEEEE;text-align: center">{{c.0}}</span>
								{%endfor%}
							</td>
						</tr>
						<tr>
							<td>
								<span title="MIPAG: {{rec.invasive_mipag}}">
									<b>MIPAG</b>: {{rec.invasive_mipag}}
								</span>
							</td>
							<td>
								{% with rec.counties as list %}
									{% for i in list.split %}
										{%if i == '*'%}
											<span style="display: inline-block;width:2em;background-color:#EEEEEE;text-align: center"> &nbsp; </span>
										{%else%}
											<span style="display: inline-block;width:2em;background-color:#EEEEEE;text-align: center">{{ i }}</span>
										{%endif%}
									{%endfor%}
								{% endwith %}
							</td>
						</tr>
						<tr>
							<td colspan="2">
                                    {%if rec.invasive == rec.invasive_mipag %}
                                        <!-- skip equal -->
                                    {%else%}
									    <b>Salicicola</b>: {{rec.invasive}} <br/>                                   
                                        {%if rec.species.caption %}    
                                        {%endif%}
                                    {%endif%}
                                    {%if rec.species.caption %}
                                    <b>Notes</b>: {{rec.species.caption|safe}}<br/>
                                    {%endif%}
                                    
                                    <b>External links</b>:
                                    {% for ann in rec.species.nameannotation_set.all %}
                                        {%if ann.url %}
                                            [<a target="_blank" href="{{ann.url}}"> * </a>] 
                                        {%endif%}
                                    {%endfor%}
{%if user.is_authenticated%}
    <br/>
    [<a target="edit" href="/names/edit/name/{{rec.species.pk}}/">Edit</a>: change invasive status or add a note]
    [<a target="annotate" href="/admin/names/nameannotation/add/?_changelist_filters=q%3D{{rec.species.pk}}&amp;plant={{rec.species.pk}}">Annotate</a>: 
    add external url with kind = 'invasive link']
{%endif%}
							</td>
                        </tr>
					</table>
					</div>
				</div>
{%endif%}
			{%endfor%}
		</div>
		<hr/> 
			<!-- FIXME Generated in {{secs}}+ seconds-->
		<br/>
	</body>
</html>

django4/names/templates/names/list_meta_new.htm
<div style="padding-left:2ex;"> <!-- background-color:yellow -->
<table border="0">
  <tr>
    <td nowrap="true">
    MA Counties
    <td>
	{%for c in tcounties %}
		<span title="{{c.1}}" style="display: inline-block;width:2em;background-color:#EEEEEE;text-align: center">{{c.0}}</span>
	{%endfor%}
    </td>
  </tr>
  <tr>
    <td>
	<span>
		{%if species.meta.rare %}
			[<b style="color:green">{{species.meta.rare}}</b>]
		{%else%}
			{%if species.meta.invasive %}
                {%if 'likely' in species.meta.invasive %}
                    [<b style="color:red">Likely Invasive</b>]
				{%elif 'Potentially' in species.meta.invasive %}
                    [<b style="color:red">Potentially Invasive</b>]
                {%else%}
                    [<b style="color:red">Invasive</b>]
				{%endif%}
			{%elif species.meta.introduced%}
				[{{species.meta.introduced|title}}]
			{%else%}
			{%endif%}
		{%endif%}
	    [{{species.meta.status}}]
	</span>
    </td>
    <td>
	{% with species.meta.counties as list %}
		{% for i in list.split %}
                   {%if i == '*'%}
                        <span style="display: inline-block;width:2em;background-color:#EEEEEE;text-align: center"> &nbsp; </span>
		   {%else%}
			<span style="display: inline-block;width:2em;background-color:#EEEEEE;text-align: center">{{ i }}</span>
                   {%endif%}
		{%endfor%}
	{% endwith %}
    </td>
  </tr>

<!-- DELETE in names -->
</table>

</div>